import { ChangeDetectionStrategy, Component, EventEmitter, Input, OnChanges, OnInit, Output, SimpleChanges, TemplateRef, ViewChild, effect, inject } from '@angular/core';
import { NgTemplateOutlet, TitleCasePipe } from '@angular/common';
import { MatDialog } from '@angular/material/dialog';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { IColumn } from '../../core/models/IColumn';
import { DataGridStore } from './store/data-grid.store';
import { FilterChangeEvent, RsivriGridHeaderComponent } from './grid-header/rsivri-grid-header.component';
import { RsivriGridBodyComponent } from './grid-body/rsivri-grid-body.component';
import { RsivriGridPagerComponent } from './grid-pager/rsivri-grid-pager.component';
import { ConfirmDialogComponent } from './dialogs/confirm-dialog.component';
import { EditRowDialogComponent } from './dialogs/edit-row-dialog.component';
import { GridSettingsDialogComponent } from './dialogs/grid-settings-dialog.component';

@Component({
  selector: 'rsivri-grid',
  standalone: true,
  imports: [RsivriGridHeaderComponent, RsivriGridBodyComponent, RsivriGridPagerComponent, NgTemplateOutlet],
  providers: [DataGridStore],
  templateUrl: './rsivri-grid.component.html',
  styleUrls: ['./rsivri-grid.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class RsivriGridComponent implements OnInit, OnChanges {
  readonly store = inject(DataGridStore);
  private readonly titleCasePipe = new TitleCasePipe();
  private readonly dialog = inject(MatDialog);

  @ViewChild(RsivriGridBodyComponent) bodyRef?: RsivriGridBodyComponent;

  data = this.store.data;
  allData = this.store.rawData;
  sort = this.store.sort;
  pageNumber = this.store.pageNumber;
  pageSize = this.store.pageSize;
  isLoading = this.store.isLoading;
  loadError = this.store.error;
  globalSearch = this.store.globalSearch;

  @Input() theme: 'dark' | 'light' = 'light';
  @Input() headerColumnLines: boolean = true;
  @Input() fetchUrl: string = '';
  @Input() fetchMethod: string = 'GET';
  @Input() fetchHeaders: Record<string, string> = {};
  @Input() authToken: string = '';
  @Input() headerRowLines: boolean = true;
  @Input() bodyRowLines: boolean = true;
  @Input() bodyColumnLines: boolean = true;
  @Input() columns: IColumn[] = [];
  @Input() tableBorder: boolean = true;
  @Input() borderRadiusTop: boolean = false;
  @Input() borderRadiusBottom: boolean = false;
  @Input() diagonalRow: boolean = false;
  @Input() dragDropRows: boolean = false;
  @Input() dragDropColumns: boolean = false;
  @Input() pagination: boolean = false;
  @Input() showFilter: boolean = false;
  @Input() showSort: boolean = false;
  @Input() showSearch: boolean = false;
  @Input() showActions: boolean = false;
  @Input() showAdd: boolean = false;
  @Input() showGridSettings: boolean = true;
  @Input() showIndex: boolean = false;
  @Input() gridMode: 'popup' | 'row' | 'batch' = 'popup';
  @Input() exportExcel: boolean = false;
  @Input() exportPDF: boolean = false;
  @Input() pagingSizes: number[] = [];
  @Input() currentPagingSize: number = 10;
  @Input() dataSource: any[] = [];
  @Input() pageListSize: number = 5;
  @Input() entrySection: string | undefined = undefined;
  @Input() remoteMode: boolean = false;
  @Input() remoteModeParams?: any;
  @Input() loadingTemplate?: TemplateRef<unknown>;
  @Input() errorTemplate?: TemplateRef<unknown>;
  @Input() emptyTemplate?: TemplateRef<unknown>;

  @Output() rowAdd = new EventEmitter<any>();
  @Output() rowEdit = new EventEmitter<any>();
  @Output() rowDelete = new EventEmitter<any>();
  @Output() batchSave = new EventEmitter<{ added: any[]; updated: { original: any; updated: any }[] }>();

  private columnsAutoGenerated = false;
  // Persists dataField order across data mutations (which regenerate columns
  // from scratch): fields no longer present are dropped, new fields land at
  // the end. Only applies on the auto-generated path -- this demo never
  // passes an explicit `columns` @Input.
  private columnOrder: string[] = [];

  private applyColumnOrder(fields: string[]): IColumn[] {
    if (this.columnOrder.length === 0) {
      return fields.map(item => ({ caption: item, dataField: item }));
    }
    const remaining = new Set(fields);
    const ordered: IColumn[] = [];
    for (const field of this.columnOrder) {
      if (remaining.has(field)) {
        ordered.push({ caption: field, dataField: field });
        remaining.delete(field);
      }
    }
    for (const field of fields) {
      if (remaining.has(field)) {
        ordered.push({ caption: field, dataField: field });
      }
    }
    return ordered;
  }

  constructor() {
    effect(() => {
      const data = this.store.rawData();
      if (this.columns.length === 0 || this.columnsAutoGenerated) {
        const fields = Object.keys(Object.assign({}, ...data));
        const nextColumns = this.applyColumnOrder(fields);
        const same = nextColumns.length === this.columns.length && nextColumns.every((c, i) => c.dataField === this.columns[i].dataField);
        if (!same) {
          this.columns = nextColumns;
        }
        this.columnsAutoGenerated = true;
      }
    });
  }

  onFilterChange(event: FilterChangeEvent): void {
    this.store.setFilter(event.dataField, event.values);
  }

  onSortToggle(dataField: string): void {
    this.store.toggleSort(dataField);
  }

  onColumnMove(event: { fromField: string; toField: string }): void {
    const order = this.columns.map(c => c.dataField);
    const fromIndex = order.indexOf(event.fromField);
    const toIndexOriginal = order.indexOf(event.toField);
    if (fromIndex === -1 || toIndexOriginal === -1 || event.fromField === event.toField) {
      return;
    }
    order.splice(fromIndex, 1);
    let insertAt = order.indexOf(event.toField);
    if (fromIndex < toIndexOriginal) {
      insertAt += 1;
    }
    order.splice(insertAt, 0, event.fromField);
    this.columnOrder = order;
    const byField = new Map(this.columns.map(c => [c.dataField, c]));
    this.columns = order.map(field => byField.get(field) ?? { caption: field, dataField: field });
  }

  onRowMove(event: { fromRow: any; toRow: any }): void {
    this.store.moveRow(event.fromRow, event.toRow);
  }

  // Column visibility + order picked from the toolbar's Grid Settings dialog.
  // Empty means "show every column" -- this layers on top of the drag-drop
  // columnOrder above rather than replacing it.
  selectedColumnFields: string[] = [];

  private visibleColumnsCacheKey: { columns: IColumn[]; selected: string[] } | null = null;
  private visibleColumnsCacheResult: IColumn[] = [];

  getVisibleColumns(): IColumn[] {
    if (this.selectedColumnFields.length === 0) {
      return this.columns;
    }
    const cache = this.visibleColumnsCacheKey;
    if (cache && cache.columns === this.columns && cache.selected === this.selectedColumnFields) {
      return this.visibleColumnsCacheResult;
    }
    const byField = new Map(this.columns.map(c => [c.dataField, c]));
    const ordered: IColumn[] = [];
    for (const field of this.selectedColumnFields) {
      const column = byField.get(field);
      if (column) {
        ordered.push(column);
      }
    }
    this.visibleColumnsCacheKey = { columns: this.columns, selected: this.selectedColumnFields };
    this.visibleColumnsCacheResult = ordered;
    return ordered;
  }

  openGridSettings(): void {
    const dialogRef = this.dialog.open(GridSettingsDialogComponent, {
      data: { columns: this.columns, selected: this.selectedColumnFields },
      panelClass: this.dialogPanelClass
    });
    const sub = dialogRef.componentInstance.selectedChange.subscribe((next: string[]) => {
      this.selectedColumnFields = next;
    });
    dialogRef.afterClosed().subscribe(() => sub.unsubscribe());
  }

  onGlobalSearchInput(event: Event): void {
    this.store.setGlobalSearch((event.target as HTMLInputElement).value);
  }

  private get dialogPanelClass(): string {
    return this.theme === 'light' ? 'rg-dialog-light' : 'rg-dialog-dark';
  }

  onRowEdit(row: any): void {
    this.dialog.open(EditRowDialogComponent, { data: { row }, panelClass: this.dialogPanelClass }).afterClosed().subscribe(updatedRow => {
      if (updatedRow) {
        this.store.updateRow(row, updatedRow);
        this.rowEdit.emit(updatedRow);
      }
    });
  }

  onAddRowClick(): void {
    if (this.gridMode === 'row') {
      this.bodyRef?.startAddingRow();
      return;
    }
    if (this.gridMode === 'batch') {
      this.bodyRef?.addBatchRow();
      return;
    }
    this.dialog.open(EditRowDialogComponent, { data: { columns: this.columns }, panelClass: this.dialogPanelClass }).afterClosed().subscribe(newRow => {
      if (newRow) {
        this.store.addRow(newRow);
        this.rowAdd.emit(newRow);
      }
    });
  }

  onRowDelete(row: any): void {
    this.dialog.open(ConfirmDialogComponent, {
      data: { title: 'Confirm delete', message: 'Are you sure you want to delete this row?' },
      panelClass: this.dialogPanelClass
    }).afterClosed().subscribe(confirmed => {
      if (confirmed) {
        this.store.removeRow(row);
        this.rowDelete.emit(row);
      }
    });
  }

  onBatchRowSave(payload: { original: any; updated: any }): void {
    this.store.updateRow(payload.original, payload.updated);
    this.rowEdit.emit(payload.updated);
  }

  onBatchRowAdd(row: any): void {
    this.store.addRow(row);
    this.rowAdd.emit(row);
  }

  onBatchCommit(payload: { added: any[]; updated: { original: any; updated: any }[] }): void {
    for (const { original, updated } of payload.updated) {
      this.store.updateRow(original, updated);
    }
    for (const row of payload.added) {
      this.store.addRow(row);
    }
    this.batchSave.emit(payload);
  }

  onSaveBatchClick(): void {
    this.bodyRef?.saveBatch();
  }

  private pagedDataCacheKey: { rows: any[]; pageNumber: number; pageSize: number; pagination: boolean; remote: boolean } | null = null;
  private pagedDataCacheResult: any[] = [];

  // Memoized so an unrelated @Input change elsewhere on this component (e.g. a
  // border toggle from the sidebar) doesn't hand the OnPush body a fresh array
  // reference every check and force it to re-render every row for nothing.
  getPagedData(): any[] {
    const rows = this.data() ?? [];
    const remote = !!this.remoteModeParams;
    if (remote || !this.pagination) {
      return rows;
    }
    const pageNumber = this.pageNumber();
    const pageSize = this.pageSize();
    const cache = this.pagedDataCacheKey;
    if (cache && cache.rows === rows && cache.pageNumber === pageNumber && cache.pageSize === pageSize
      && cache.pagination === this.pagination && cache.remote === remote) {
      return this.pagedDataCacheResult;
    }
    const result = rows.slice(pageNumber * pageSize, (pageNumber + 1) * pageSize);
    this.pagedDataCacheKey = { rows, pageNumber, pageSize, pagination: this.pagination, remote };
    this.pagedDataCacheResult = result;
    return result;
  }

  private getDisplayedCaptions(): string[] {
    return this.getVisibleColumns().map(column => this.titleCasePipe.transform(column.caption));
  }

  onExportExcelClick(): void {
    const rows = this.getPagedData();
    const captions = this.getDisplayedCaptions();
    const mapped = rows.map(row => Object.fromEntries(
      this.getVisibleColumns().map((column, i) => [captions[i], row[column.dataField]])
    ));
    const worksheet = XLSX.utils.json_to_sheet(mapped);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Sheet1');
    XLSX.writeFile(workbook, 'export.xlsx');
  }

  onExportPdfClick(): void {
    const rows = this.getPagedData();
    const doc = new jsPDF({ orientation: 'landscape' });
    autoTable(doc, {
      head: [this.getDisplayedCaptions()],
      body: rows.map(row => this.getVisibleColumns().map(column => String(row[column.dataField] ?? ''))),
      theme: 'grid',
      styles: { fontSize: 9, cellPadding: 3, overflow: 'linebreak' },
      headStyles: { fillColor: [119, 119, 119], textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [245, 245, 245] },
    });
    doc.save('export.pdf');
  }

  ngOnInit() {
    this.loadData();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['dataSource'] && !changes['dataSource'].firstChange) {
      this.loadData();
    }
  }

  private buildRequestHeaders(): Record<string, string> | undefined {
    const headers = { ...(this.fetchHeaders ?? {}) };
    if (this.authToken) {
      headers['Authorization'] = `Bearer ${this.authToken}`;
    }
    return Object.keys(headers).length > 0 ? headers : undefined;
  }

  fetchNow(): void {
    this.loadData();
  }

  private loadData(): void {
    if (this.remoteMode) {
      const endpoint = new URL(this.remoteModeParams.endpoint);
      if (this.dataSource.length > 0) {
        this.store.setData(this.dataSource, true);
      } else {
        this.store.fetchData(endpoint.href, this.remoteModeParams.aliases.data, true, 'size', this.fetchMethod, this.buildRequestHeaders());
      }
    } else {
      if (this.dataSource.length > 0) {
        this.store.setData(this.dataSource, false);
      } else {
        if (this.fetchUrl !== '') {
          this.store.fetchData(this.fetchUrl, this.entrySection, false, undefined, this.fetchMethod, this.buildRequestHeaders());
        } else {
          this.store.setData(this.dataSource, false);
        }
      }
    }
  }
}
