import { Component, EventEmitter, Input, OnChanges, OnInit, Output, SimpleChanges, TemplateRef, ViewChild, effect, inject } from '@angular/core';
import { NgTemplateOutlet, TitleCasePipe } from '@angular/common';
import { MatDialog } from '@angular/material/dialog';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { IColumn } from '../../core/models/IColumn';
import { DataGridStore } from './store/data-grid.store';
import { FilterChangeEvent, RsivriGridHeaderComponent } from './grid-header/rsivri-grid-header.component';
import { RsivriGridBodyComponent } from './grid-body/rsivri-grid-body.component';
import { RsivriGridPagerComponent } from './grid-pager/rsivri-grid-pager.component';
import { ConfirmDialogComponent } from './dialogs/confirm-dialog.component';
import { EditRowDialogComponent } from './dialogs/edit-row-dialog.component';

@Component({
  selector: 'rsivri-grid',
  standalone: true,
  imports: [RsivriGridHeaderComponent, RsivriGridBodyComponent, RsivriGridPagerComponent, NgTemplateOutlet],
  providers: [DataGridStore],
  templateUrl: './rsivri-grid.component.html',
  styleUrls: ['./rsivri-grid.component.css']
})
export class RsivriGridComponent implements OnInit, OnChanges {
  readonly store = inject(DataGridStore);
  private readonly titleCasePipe = new TitleCasePipe();
  private readonly dialog = inject(MatDialog);

  @ViewChild(RsivriGridBodyComponent) bodyRef?: RsivriGridBodyComponent;

  data = this.store.data;
  allData = this.store.rawData;
  sort = this.store.sort;
  pageNumber = this.store.pageNumber;
  pageSize = this.store.pageSize;
  isLoading = this.store.isLoading;
  loadError = this.store.error;
  globalSearch = this.store.globalSearch;

  @Input() headerColumnLines: boolean = true;
  @Input() fetchUrl: string = '';
  @Input() fetchMethod: string = 'GET';
  @Input() fetchHeaders: Record<string, string> = {};
  @Input() authToken: string = '';
  @Input() headerRowLines: boolean = true;
  @Input() bodyRowLines: boolean = true;
  @Input() bodyColumnLines: boolean = true;
  @Input() columns: IColumn[] = [];
  @Input() tableBorder: boolean = true;
  @Input() borderRadiusTop: boolean = false;
  @Input() borderRadiusBottom: boolean = false;
  @Input() diagonalRow: boolean = false;
  @Input() pagination: boolean = false;
  @Input() showFilter: boolean = false;
  @Input() showSort: boolean = false;
  @Input() showSearch: boolean = false;
  @Input() showActions: boolean = false;
  @Input() showAdd: boolean = false;
  @Input() gridMode: 'popup' | 'batch' = 'popup';
  @Input() exportExcel: boolean = false;
  @Input() exportPDF: boolean = false;
  @Input() pagingSizes: number[] = [];
  @Input() currentPagingSize: number = 10;
  @Input() dataSource: any[] = [];
  @Input() pageListSize: number = 5;
  @Input() entrySection: string | undefined = undefined;
  @Input() remoteMode: boolean = false;
  @Input() remoteModeParams?: any;
  @Input() loadingTemplate?: TemplateRef<unknown>;
  @Input() errorTemplate?: TemplateRef<unknown>;

  @Output() rowAdd = new EventEmitter<any>();
  @Output() rowEdit = new EventEmitter<any>();
  @Output() rowDelete = new EventEmitter<any>();

  private columnsAutoGenerated = false;

  constructor() {
    effect(() => {
      const data = this.store.data();
      if (this.columns.length === 0 || this.columnsAutoGenerated) {
        const result = Object.keys(Object.assign({}, ...data));
        this.columns = result.map(item => ({ caption: item, dataField: item }));
        this.columnsAutoGenerated = true;
      }
    });
  }

  onFilterChange(event: FilterChangeEvent): void {
    this.store.setFilter(event.dataField, event.values);
  }

  onSortToggle(dataField: string): void {
    this.store.toggleSort(dataField);
  }

  onGlobalSearchInput(event: Event): void {
    this.store.setGlobalSearch((event.target as HTMLInputElement).value);
  }

  onRowEdit(row: any): void {
    this.dialog.open(EditRowDialogComponent, { data: { row } }).afterClosed().subscribe(updatedRow => {
      if (updatedRow) {
        this.store.updateRow(row, updatedRow);
        this.rowEdit.emit(updatedRow);
      }
    });
  }

  onAddRowClick(): void {
    if (this.gridMode === 'batch') {
      this.bodyRef?.startAddingRow();
      return;
    }
    this.dialog.open(EditRowDialogComponent, { data: { columns: this.columns } }).afterClosed().subscribe(newRow => {
      if (newRow) {
        this.store.addRow(newRow);
        this.rowAdd.emit(newRow);
      }
    });
  }

  onRowDelete(row: any): void {
    this.dialog.open(ConfirmDialogComponent, {
      data: { title: 'Confirm delete', message: 'Are you sure you want to delete this row?' }
    }).afterClosed().subscribe(confirmed => {
      if (confirmed) {
        this.store.removeRow(row);
        this.rowDelete.emit(row);
      }
    });
  }

  onBatchRowSave(payload: { original: any; updated: any }): void {
    this.store.updateRow(payload.original, payload.updated);
    this.rowEdit.emit(payload.updated);
  }

  onBatchRowAdd(row: any): void {
    this.store.addRow(row);
    this.rowAdd.emit(row);
  }

  private getDisplayedRows(): any[] {
    const rows = this.data() ?? [];
    if (!this.remoteModeParams && this.pagination) {
      return rows.slice(this.pageNumber() * this.pageSize(), (this.pageNumber() + 1) * this.pageSize());
    }
    return rows;
  }

  private getDisplayedCaptions(): string[] {
    return this.columns.map(column => this.titleCasePipe.transform(column.caption));
  }

  onExportExcelClick(): void {
    const rows = this.getDisplayedRows();
    const captions = this.getDisplayedCaptions();
    const mapped = rows.map(row => Object.fromEntries(
      this.columns.map((column, i) => [captions[i], row[column.dataField]])
    ));
    const worksheet = XLSX.utils.json_to_sheet(mapped);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Sheet1');
    XLSX.writeFile(workbook, 'export.xlsx');
  }

  onExportPdfClick(): void {
    const rows = this.getDisplayedRows();
    const doc = new jsPDF({ orientation: 'landscape' });
    autoTable(doc, {
      head: [this.getDisplayedCaptions()],
      body: rows.map(row => this.columns.map(column => String(row[column.dataField] ?? ''))),
      theme: 'grid',
      styles: { fontSize: 9, cellPadding: 3, overflow: 'linebreak' },
      headStyles: { fillColor: [119, 119, 119], textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [245, 245, 245] },
    });
    doc.save('export.pdf');
  }

  ngOnInit() {
    this.loadData();
  }

  ngOnChanges(changes: SimpleChanges): void {
    const reloadKeys = ['fetchUrl', 'fetchMethod', 'fetchHeaders', 'authToken', 'entrySection', 'remoteMode', 'dataSource', 'remoteModeParams'];
    const shouldReload = reloadKeys.some(key => changes[key] && !changes[key].firstChange);
    if (shouldReload) {
      this.loadData();
    }
  }

  private buildRequestHeaders(): Record<string, string> | undefined {
    const headers = { ...(this.fetchHeaders ?? {}) };
    if (this.authToken) {
      headers['Authorization'] = `Bearer ${this.authToken}`;
    }
    return Object.keys(headers).length > 0 ? headers : undefined;
  }

  private loadData(): void {
    if (this.remoteMode) {
      const endpoint = new URL(this.remoteModeParams.endpoint);
      if (this.dataSource.length > 0) {
        this.store.setData(this.dataSource, true);
      } else {
        this.store.fetchData(endpoint.href, this.remoteModeParams.aliases.data, true, 'size', this.fetchMethod, this.buildRequestHeaders());
      }
    } else {
      if (this.dataSource.length > 0) {
        this.store.setData(this.dataSource, false);
      } else {
        if (this.fetchUrl !== '') {
          this.store.fetchData(this.fetchUrl, this.entrySection, false, undefined, this.fetchMethod, this.buildRequestHeaders());
        } else {
          this.store.setData(this.dataSource, false);
        }
      }
    }
  }
}
